### ISSUE TITLE
.modelPath has back slashes

### ISSUE THREAD

**Issue by lauracmurphy** [qupath/qupath-extension-instanseg#108]
Problem 
When you create a script with an InstanSeg run in it using the Workflow tab, the model path has back slashes so when you try and run the script it errors out.

Solution
Make the path all Linuxy so QuPath likes it.

<img width="423" alt="image" src="https://github.com/user-attachments/assets/f59edca7-849a-4f7c-9966-ffd183658e01">

**Comment by alanocallaghan** [comment]
Related to https://github.com/qupath/qupath-extension-instanseg/issues/98 in some way I suspect

**Comment by alanocallaghan** [comment]
Although, it looks like the error there is related to the quote character, I suspect you might have a funny unicode quote somehow

**Comment by lauracmurphy** [comment]
Oh sorry, should have checked closed issues.

It's fixed by changing to forward slashes and leaving the quotes so I'm pretty sure it's that.

**Comment by alanocallaghan** [comment]
Which extension version are you using?

**Comment by petebankhead** [comment]
The extension version is currently tied to the release candidate version - this *should* be fixed in v0.6.0-rc3 (but if you have run InstanSeg on an image in an earlier version, the script with the wrong slashes will still be in the command history and won't update automatically).

**Comment by lauracmurphy** [comment]
Yeah sorry, I was on a different computer from my main one so didn't notice I was on rc2.

Poor show me.
