### ISSUE TITLE
brightfield nuclei and cells model?

### ISSUE THREAD

**Issue by r100gs** [qupath/qupath-extension-instanseg#95]
Hello,

the extension is running fine and brightfield nuclei detection is good, but is there a model for nuclei and cell detection in brightfield?

Thank you,
Stefan

**Comment by petebankhead** [comment]
Not currently. We certainly plan to release more models in the future - and to continue improving the method - although it will be at least a couple of weeks before we can do this.

A major limitation is the availability of open training data. I am aware of [this](https://zenodo.org/records/10560728), but it is licensed `CC BY-NC-SA 4.0` and this has restrictions that aren't compatible with open-source - and it's not clear whether models trained on this data would have the same restrictions (despite the peer-reviewed publication stating that the data is shared under [a difference license](https://www.sciencedirect.com/science/article/pii/S0169260724002104#da1)).

For a discussion on why 'non-commercial' clauses are problematic, see https://freedomdefined.org/Licenses/NC

In the meantime, you can try the fluorescence model after selecting the input channels to include color-deconvolved channels from the brightfield image. I find that this sometimes works quite well, but not consistently enough to recommend in general - which makes sense, as it was not trained on any brightfield images.
